export const ACTIVATE_BASEMAP = 'ACTIVATE_BASEMAP';
export const TOGGLE_LAYER = 'TOGGLE_LAYER';

export const UPDATE_QUERY = 'UPDATE_QUERY';
export const SELECT_OFFICE = 'SELECT_OFFICE';
export const NEAREST_OFFICES = 'NEAREST_OFFICES';

export const HIDE_AUTOCOMPLETE_RESULTS = 'HIDE_AUTOCOMPLETE_RESULTS';
export const SHOW_AUTOCOMPLETE_RESULTS = 'SHOW_AUTOCOMPLETE_RESULTS';

export const CHANGE_VIEW = 'CHANGE_VIEW';
